// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA94OP87D8-q9Eue4-5WMo5N4DOABujRos',
    appId: '1:90779758378:web:6d73184b3a04be1c2bb853',
    messagingSenderId: '90779758378',
    projectId: 'qrcodechatapp',
    authDomain: 'qrcodechatapp.firebaseapp.com',
    storageBucket: 'qrcodechatapp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzwBl53H57tcEDn_C5nDWOLF2erTe5ZPU',
    appId: '1:90779758378:android:f34caa625ae2e9352bb853',
    messagingSenderId: '90779758378',
    projectId: 'qrcodechatapp',
    storageBucket: 'qrcodechatapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBP-LMTcbskAGLEhJD71sL9N4fOX3JPdRY',
    appId: '1:90779758378:ios:ddfe1df0a4e8f9912bb853',
    messagingSenderId: '90779758378',
    projectId: 'qrcodechatapp',
    storageBucket: 'qrcodechatapp.firebasestorage.app',
    iosBundleId: 'com.example.qrChatApp',
  );
}
